### ISSUE TITLE
app is crash 

### ISSUE THREAD

**Issue by gongwj1119** [haiyangwu/mediasoup-client-android#13]
vsersion 3.0.4-beta-2 is crash
/org.mediasoup.client.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mediasoup.client.demo, PID: 13676
    java.lang.UnsatisfiedLinkError: No implementation found for void org.mediasoup.droid.Logger.nativeSetDefaultHandler() (tried Java_org_mediasoup_droid_Logger_nativeSetDefaultHandler and Java_org_mediasoup_droid_Logger_nativeSetDefaultHandler__)
        at org.mediasoup.droid.Logger.nativeSetDefaultHandler(Native Method)
        at org.mediasoup.droid.Logger.setDefaultHandler(Logger.java:39)
        at org.mediasoup.client.demo.Application.onCreate(Application.java:13)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by haiyangwu** [comment]
Update to the latest version. It should be fixed.
