### ISSUE TITLE
No implementation found for long org.mediasoup.droid.Device.nativeNewDevice()

### ISSUE THREAD

**Issue by footniko** [haiyangwu/mediasoup-client-android#26]
After I execute `Device mediaDevice = new Device();` I get the following error:
```
    --------- beginning of crash
2020-05-17 17:42:53.386 com.example.mediaclient E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mediaclient, PID: 3644
    java.lang.UnsatisfiedLinkError: No implementation found for long org.mediasoup.droid.Device.nativeNewDevice() (tried Java_org_mediasoup_droid_Device_nativeNewDevice and Java_org_mediasoup_droid_Device_nativeNewDevice__)
        at org.mediasoup.droid.Device.nativeNewDevice(Native Method)
        at org.mediasoup.droid.Device.<init>(Device.java:8)
        at com.example.mediaclient.MainActivity$1$1.run(MainActivity.java:88)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by footniko** [comment]
@haiyangwu `MediasoupClient.initialize(getApplicationContext());` is missed in readme :(
