### ISSUE TITLE
v7a invalid codec.mimetype

### ISSUE THREAD

**Issue by iQuick** [haiyangwu/mediasoup-client-android#29]
Compiling v8a version can be used normally, but only using v7a will report an error.

```
E/RoomClient: joinRoom() failed:
    org.mediasoup.droid.MediasoupException: invalid codec.mimeType
E/RoomClient: org.mediasoup.droid.MediasoupException: invalid codec.mimeType
        at org.mediasoup.droid.Device.nativeLoad(Native Method)
        at org.mediasoup.droid.Device.load(Device.java:19)
        at org.mediasoup.droid.lib.RoomClient.joinImpl(RoomClient.java:669)
        at org.mediasoup.droid.lib.RoomClient.access$500(RoomClient.java:38)
        at org.mediasoup.droid.lib.RoomClient$2.lambda$onOpen$0$RoomClient$2(RoomClient.java:574)
        at org.mediasoup.droid.lib.-$$Lambda$RoomClient$2$1yrKTPoWaRxWuD7Kk1QcDNV7v7Y.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:192)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by rawnsley** [comment]
I can reproduce the same problem with the [demo project](https://github.com/haiyangwu/mediasoup-demo-android) by commenting out every abiFilter in the build.gradle file except _armeabi-v7a_ and running it on a 64-bit capable ARM device.

Finding a work around would be important to me because each ABI contributes an extra 5MB to the final APK file.

**Comment by iQuick** [comment]
@rawnsley 
Ok, i got it. Thank you very much !

**Comment by haiyangwu** [comment]
@iQuick Thx for reporting, it seems a bug related to `move` syntax. A fix commits already pushed and it works well.

**Comment by tirrcute** [comment]
when i use beta-3，Compiling v8a is normally, but only using v7a will report an error , the remote peerview doesn't work and show nothing , it cause:
E/RoomClient: "newConsumer" request failed:
E/RoomClient: org.mediasoup.droid.MediasoupException: Session error code: ERROR_CONTENT. Session error description: Failed to set remote audio description send parameters..
E/RoomClient: org.mediasoup.droid.MediasoupException: Session error code: ERROR_CONTENT. Session error description: Failed to set remote audio description send parameters..
        at org.mediasoup.droid.RecvTransport.nativeConsume(Native Method)
        at org.mediasoup.droid.RecvTransport.consume(RecvTransport.java:48)
        at org.mediasoup.droid.lib.RoomClient.onNewConsumer(RoomClient.java:1052)
        at org.mediasoup.droid.lib.RoomClient.access$300(RoomClient.java:38)
        at org.mediasoup.droid.lib.RoomClient$2.lambda$onRequest$2$RoomClient$2(RoomClient.java:596)
        at org.mediasoup.droid.lib.-$$Lambda$RoomClient$2$8B9dCuDRW2LL5UzQlkr80_pqLG0.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:755)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
E/RoomClient: unknown protoo notification.method downlinkBwe
