### ISSUE TITLE
using v7a in 64 cpu cause peerview show nothing

### ISSUE THREAD

**Issue by tirrcute** [haiyangwu/mediasoup-client-android#35]
when i use beta-3 version，Compiling client deemo using v8a is normally, but only using v7a will report an error , the remote peerview doesn't work and show nothing , it cause:
```
E/RoomClient: "newConsumer" request failed:
E/RoomClient: org.mediasoup.droid.MediasoupException: Session error code: ERROR_CONTENT. Session error description: Failed to set remote audio description send parameters..
E/RoomClient: org.mediasoup.droid.MediasoupException: Session error code: ERROR_CONTENT. Session error description: Failed to set remote audio description send parameters..
at org.mediasoup.droid.RecvTransport.nativeConsume(Native Method)
at org.mediasoup.droid.RecvTransport.consume(RecvTransport.java:48)
at org.mediasoup.droid.lib.RoomClient.onNewConsumer(RoomClient.java:1052)
at org.mediasoup.droid.lib.RoomClient.access$300(RoomClient.java:38)
at org.mediasoup.droid.lib.RoomClient$2.lambda$onRequest$2$RoomClient$2(RoomClient.java:596)
at org.mediasoup.droid.lib.-$$Lambda$RoomClient$2$8B9dCuDRW2LL5UzQlkr80_pqLG0.run(lambda)
at android.os.Handler.handleCallback(Handler.java:755)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
E/RoomClient: unknown protoo notification.method downlinkBwe
```

**Comment by J1aDong** [comment]
+1

**Comment by QingDouEr** [comment]
+1

**Comment by Azamatjon** [comment]
+1

**Comment by Azamatjon** [comment]
@tirrcute Did you find the solution?
