### ISSUE TITLE
Failed to set remote audio description send parameters

### ISSUE THREAD

**Issue by jackzhanghai** [haiyangwu/mediasoup-client-android#36]
07-02 15:34:11.806 23566-23625/org.mediasoup.droid.demo E/RoomClient: "newConsumer" request failed:
07-02 15:34:11.806 23566-23625/org.mediasoup.droid.demo E/RoomClient: org.mediasoup.droid.MediasoupException: Failed to set remote offer sdp: Failed to set remote audio description send parameters.
07-02 15:34:11.807 23566-23625/org.mediasoup.droid.demo E/RoomClient: org.mediasoup.droid.MediasoupException: Failed to set remote offer sdp: Failed to set remote audio description send parameters.
        at org.mediasoup.droid.RecvTransport.nativeConsume(Native Method)
        at org.mediasoup.droid.RecvTransport.consume(RecvTransport.java:48)
        at org.mediasoup.droid.lib.RoomClient.onNewConsumer(RoomClient.java:1052)
        at org.mediasoup.droid.lib.RoomClient.access$300(RoomClient.java:38)
        at org.mediasoup.droid.lib.RoomClient$2.lambda$onRequest$2$RoomClient$2(RoomClient.java:596)
        at org.mediasoup.droid.lib.-$$Lambda$RoomClient$2$8B9dCuDRW2LL5UzQlkr80_pqLG0.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by fluidwl** [comment]
So do I. Browser is find, but android phone throw "Failed to set remote audio description send parameters." exception.

**Comment by Gleejay** [comment]
I, too, had the same problem, and I was anxious to solve it

**Comment by fluidwl** [comment]
> I, too, had the same problem, and I was anxious to solve it

I fix this problem by modified source code.

**Comment by Gleejay** [comment]
> > I, too, had the same problem, and I was anxious to solve it
> 
> I fix this problem by modified source code.

Well done, Can you tell me how you did it ? ths ~

**Comment by Sun-Cj** [comment]
> > 我也有同样的问题，我很想解决这个问题
> 
> 我通过修改后的源代码解决了这个问题。

您好，可以分享一下你是如何解决的吗？

**Comment by J1aDong** [comment]
> > I, too, had the same problem, and I was anxious to solve it
> 
> I fix this problem by modified source code.

@fluidwl  Can you share how to solve it

**Comment by KurdAppDev** [comment]
I think it because opus audio codec solved this by adding  PCMU media Codecs to config.js to the above 'audio/opus' media Codec
mediasoup demo server

```
                                        {
						kind: 'audio',
						mimeType: 'audio/PCMU',
						preferredPayloadType: 0,
						clockRate: 8000
					},
					{
						kind: 'audio',
						mimeType: 'audio/PCMA',
						preferredPayloadType: 8,
						clockRate: 8000
					},
                                        {
						kind: 'audio',
						mimeType: 'audio/opus',
						clockRate: 48000,
						channels: 2
					},
```

**Comment by hyperandroid** [comment]
This is fixed by upgrading webrtc to latest version.
I have compiled webrtc, upgraded libmediasoup and fixed some minor API breaking changes and have android armv7a working as expected.

**Comment by android-little-boy** [comment]
> This is fixed by upgrading webrtc to latest version.
> I have compiled webrtc, upgraded libmediasoup and fixed some minor API breaking changes and have android armv7a working as expected.

Hello, the same problem also occurred when I used the author's library, and I could not solve it. Could you please share your source code?

**Comment by hyperandroid** [comment]
Try using the following aar file instead of the artifact in the demo project.
https://www.dropbox.com/s/3t324fia6s0qtku/mediasoup-client.aar?dl=0
Let me know if this works for you. Feel free to contact me directly. My github username at gmail.

**Comment by android-little-boy** [comment]
> Try using the following aar file instead of the artifact in the demo project.
> https://www.dropbox.com/s/3t324fia6s0qtku/mediasoup-client.aar?dl=0
> Let me know if this works for you. Feel free to contact me directly. My github username at gmail.

Thank you for your generosity. It is a pity that your library is not applicable to my equipment, and it will have new exceptions.Recently I solved the audio failure problem caused by Haiyangwu's library by switching to a 64-bit runtime environment.Thanks anyway.
