### ISSUE TITLE
No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData

### ISSUE THREAD

**Issue by lanzhu1993** [haiyangwu/mediasoup-client-android#51]
2021-04-17 22:49:04.150 10455-16973/? E/zygote64: No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)
2021-04-17 22:49:04.151 10455-16973/? E/AndroidRuntime: FATAL EXCEPTION: AudioTrackJavaThread
    Process: cn.lecent.prisonroom.guards, PID: 10455
    java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)
        at org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(Native Method)
        at org.webrtc.voiceengine.WebRtcAudioTrack.access$400(WebRtcAudioTrack.java:28)
        at org.webrtc.voiceengine.WebRtcAudioTrack$AudioTrackThread.run(WebRtcAudioTrack.java:147)

**Comment by grebulon** [comment]
I added more info on that at: https://github.com/haiyangwu/mediasoup-client-android/issues/54#issuecomment-1157475077
